### ISSUE TITLE
Viewing words does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by Logan84** [CompCogNeuro/sims#8]
When following the steps, there have been two times that the simulation crashed. When hitting the [Wt Words] button, the simulation crashes. When hitting the TrainEnv and then on Words to see a list of all the words, the simulation crashes.

**Comment by rcoreilly** [comment]
could you run from a terminal and post the stack traces of the crashes?

**Comment by rcoreilly** [comment]
btw I just got a crash in Wt Words by keeping the window open and hitting the button again -- I will fix this one -- is it the same that you got?

```Go
panic: runtime error: comparing uncomparable type []string

goroutine 13 [running]:
github.com/goki/gi/gi.(*WindowList).FindData(0x6acd1c0, 0x4f25300, 0xc015c6e5e8, 0x0, 0xc000702400)
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:2491 +0xe0
github.com/goki/gi/gi.RecycleStdDialog(0x4f25300, 0xc015c6e5e8, 0xc01663d590, 0xe, 0x0, 0x0, 0x0, 0xc033860101, 0xc0001b9108, 0xc0001b9130)
	/Users/oreilly/go/src/github.com/goki/gi/gi/dialogs.go:467 +0x4e
github.com/goki/gi/giv.SliceViewDialog(0xc0008ec000, 0x4f25300, 0xc015c6e5e8, 0xc01663d590, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
```

**Comment by rcoreilly** [comment]
I can't replicate the 2nd crash though, on mac

**Comment by rcoreilly** [comment]
first one is fixed.
